### PR TITLE
CORS

### PR DESCRIPTION
**Pull request by alexplump1**
Frontend (browsers) can now use backend APIs.

### CODE REVIEW

**Review by ltrinks — CHANGES_REQUESTED** [review]
Can you make cors use all REST methods

**Review by ltrinks — CHANGES_REQUESTED** [review]
Sign in and creation works from the frontend, but when closing the tab and re-entering something is going wrong and it forgets the previous sign in and new sign in does not work

**Comment by alexplump1** [comment]
The sign in page currently does not sign one in. You can compare the code in signup.component.ts and login.component.ts. The only way to login currently is by creating an account. 

Additionally, signed_in is stored in session storage, so new tabs will not keep session alive. /login currently doesn't return a session id that I could store in local storage. Is that something we want to implement?

**Comment by ltrinks** [comment]
> The sign in page currently does not sign one in. You can compare the code in signup.component.ts and login.component.ts. The only way to login currently is by creating an account.
> 
> Additionally, signed_in is stored in session storage, so new tabs will not keep session alive. /login currently doesn't return a session id that I could store in local storage. Is that something we want to implement?

Ah okay that makes sense! /login sets a cookie on the user's browser so it is capable of remembering sign in across tabs / usages. Perhaps you can make the main page be profile and when a request gets a 401 redirect to the "oops you're not signed in" page.

**Pull request merged**
